config/routes.rb
Rails.application.routes.draw do
  get "tourist_areas/index"
  root "pages#home"
  get  "/help",    to: "pages#help"
  get  "/about",   to: "pages#about"
  get  "/contact", to: "pages#contact"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :categories, only: :show
  resources :tourist_areas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tourist_areas, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :tourist_area tuan
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :tourist_area
end

app/models/tourist_area.rb
class TouristArea < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
end

app/models/touristarea.rb
class Touristarea < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  attr_accessor :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  has_many :ratings, dependent: :destroy
  has_many :tourist_areas, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def self.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? remember_token
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = t(".please")
        redirect_to login_url
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find params[:id]
    @tourist_areas = @category.tourist_areas.paginate page: params[:page]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user &.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to root_url
    else
      flash.now[:danger] = t(".flash_login")
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tourist_areas_controller.rb
class TouristAreasController < ApplicationController
  before_action :logged_in_user, except: [:index, :show]
  before_action :correct_user, only: :destroy
  before_action :get_tourist_area, only: [:show, :update, :edit]

  def new
    @tourist_area = TouristArea.new
  end

  def index
    @tourist_areas = TouristArea.paginate page: params[:page]
  end

  def show; end

  def create
    @tourist_area = current_user.tourist_areas.build tourist_area_params
    if @tourist_area.save
      flash[:success] = t(".success")
      redirect_to root_url
    else
      render "pages/home"
    end
  end

  def edit; end

  def update
    if @tourist_area.update tourist_area_params
      flash[:success] = t(".success")
      redirect_to @tourist_area
    else
      render "edit"
    end
  end

  def destroy
    @tourist_area.destroy
    flash[:success] = t(".success")
    redirect_to request.referer || root_url
  end

  private

    def tourist_area_params
      params.require(:tourist_area).permit(:name, :address, :phone_number, :introduce, :user_id, :category_id)
    end

    def correct_user
      redirect_to root_url unless current_user.tourist_areas.find params[:id]
    end

    def get_tourist_area
      @tourist_area = TouristArea.find params[:id]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def show; end

  def new
    @user = User.new
  end

  def index
    @users = User.paginate page: params[:page]
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t(".flash_updated")
      redirect_to root_path
    else
      render :edit
    end
  end

  def create
    @user = User.new user_params
    @user.save ? (redirect_to root_path) : (render :new)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t(".flash_deleted")
    redirect_to users_url
  end

  private

    def set_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t(".railsapp")
    page_title.empty? ? base_title : "#{page_title} #{base_title}"
  end

  def list_categories
    Category.paginate page: params[:page]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    user == current_user
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find(user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find(user_id)
      if user &.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user? user
    user == current_user
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = { size: 80 }
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @category.name %>
        <h1><%= link_to t(".create_tourist_area"), new_tourist_area_path %></h1>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @tourist_areas.any? %>
      <h3><%= t(".touristarea", touristareas_count: @tourist_areas.count) %></h3>
      <%= will_paginate @tourist_areas %>
      <ol class="tourist">
        <%= render @tourist_areas %>
      </ol>
      <%= will_paginate @tourist_areas %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".copyright" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".reviewtour"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(".category") %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% list_categories.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to t(".touristarea"), tourist_areas_url %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t(".log_out"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pages/help.html.erb
<h1><%= t ".help" %></h1>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>
  <h2><%= t ".intro" %></h2>
  <%= link_to t(".sign"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("download.jpeg", alt: t(".logo")),'#' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".texterror", error: pluralize(object.errors.count, t(".error")) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

app/views/tourist_areas/_form.html.erb
<%= form_for tourist_area do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label t ".name" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label t ".address" %>
  <%= f.text_field :address, class: "form-control" %>
  <%= f.label t ".phonenumber" %>
  <%= f.text_field :phone_number, class: "form-control" %>
  <%= f.label t ".categoryid" %>
  <%= f.collection_select :category_id, list_categories, :id, :name %>
  <%= f.label t ".introduce" %>
  <%= f.text_area :introduce, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tourist_areas/_tourist_area.html.erb
<li id="tourist_area-<%= tourist_area.id %>">
  <span class="content">
    <%= link_to tourist_area.name, tourist_area %>
    <%= t ".createby" %>
    <%= link_to tourist_area.user.name, tourist_area.user %>
    <%= t ".at" %>
    <%= tourist_area.created_at %>
  </span>
  <span class="timestamp">
    <% if current_user? tourist_area.user %>
      <%= link_to t(".delete"), tourist_area, method: :delete, data: { confirm: t(".yousure") } %>
      <%= link_to t(".update"), edit_tourist_area_path(tourist_area.id) %>
    <% end %>
  </span>
</li>

app/views/tourist_areas/edit.html.erb
<% provide :title, t(".edit_tourist_area") %>
<% provide :button_text, t(".save_change") %>
<h1><%= t ".edit_tourist_area" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", tourist_area: @tourist_area %>
  </div>
</div>

app/views/tourist_areas/index.html.erb
<% provide :title, t(".touristarea") %>
<h1><%= t ".touristarea" %></h1>
<h1><%= link_to t(".create_tourist_area"), new_tourist_area_path %></h1>
<%= will_paginate @tourist_areas %>
<ul class="tourist">
  <%= render @tourist_areas %>
</ul>
<%= will_paginate @tourist_areas %>

app/views/tourist_areas/new.html.erb
<% provide :title, t(".new_tourist_area") %>
<% provide :button_text, t(".create_tourist_area") %>
<h1><%= t ".new_tourist_area" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", tourist_area: @tourist_area %>
  </div>
</div>

app/views/tourist_areas/show.html.erb
<% provide :title, @tourist_area.name %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h3><%= @tourist_area.name %></h1>
      <h5><%= t ".address", address: @tourist_area.address %></h1>
      <h5><%= t ".phonenumber", phonenumber: @tourist_area.phone_number %></h1>
      <h5><%= t ".introduce", introduce: @tourist_area.introduce %></h1>
      <h5><%= t ".createby", createby: @tourist_area.user.name %></h1>
      <h5><%= t ".region", region: @tourist_area.category.name %></h1>
      <%= link_to t(".writereview"), "#", class: "btn btn-lg btn-primary" %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= t ".allreview" %></h3>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t(".name") %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label t(".email") %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label t(".password")%>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label t(".password_confirmation") %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
    | <%= link_to "delete", user, method: :delete,data: { confirm: t(".you_sure") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".edit_user") %>
<% provide :button_text, t(".save") %>
<h1><%= t".update_profile"%></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".all_users") %>
<h1><%= t".all_users" %></h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".signup") %>
<% provide :button_text, t(".textsubmit") %>
<h1><%= t".signup" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>